// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2_ap1_20180618.DAL;

namespace Parcial2_ap1_20180618.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210308044411_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Parcial2_ap1_20180618.Entidades.Proyectos", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("TiempoTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProyectoId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Parcial2_ap1_20180618.Entidades.ProyectosDetalle", b =>
                {
                    b.Property<int>("ProyectoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoTareaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProyectoDetalleId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("ProyectosDetalle");
                });

            modelBuilder.Entity("Parcial2_ap1_20180618.Entidades.TiposTareas", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoId");

                    b.ToTable("TiposTareas");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Análisis",
                            Requerimiento = "Analizar la opción de clientes",
                            Tiempo = 120
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Diseño",
                            Requerimiento = "Hacer un diseño excelente",
                            Tiempo = 60
                        },
                        new
                        {
                            TipoId = 3,
                            Descripcion = "Programación",
                            Requerimiento = "Programar todo el registro",
                            Tiempo = 240
                        },
                        new
                        {
                            TipoId = 4,
                            Descripcion = "Prueba",
                            Requerimiento = "Probar con mucho cuidado",
                            Tiempo = 30
                        });
                });

            modelBuilder.Entity("Parcial2_ap1_20180618.Entidades.ProyectosDetalle", b =>
                {
                    b.HasOne("Parcial2_ap1_20180618.Entidades.Proyectos", null)
                        .WithMany("ProyectosDetalle")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parcial2_ap1_20180618.Entidades.Proyectos", b =>
                {
                    b.Navigation("ProyectosDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
